project_id = "kaetsegwzfvkermjokmh"

[functions.generate-show-content]
verify_jwt = true

[functions.gmail-callback]
verify_jwt = false

[functions.get-gmail-auth-url]
verify_jwt = false

[functions.fetch-venue-events]
verify_jwt = true

[functions.update-all-venue-events]
verify_jwt = true