// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaetsegwzfvkermjokmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZXRzZWd3emZ2a2VybWpva21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzY2NDEsImV4cCI6MjA3MTcxMjY0MX0.8Ddj1LUceOBqNuH8cRuupsGBpVLYd1S78OoY7Ubgi-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});